### ISSUE TITLE
Pipe error on Windows

### ISSUE THREAD

**Issue by SLetterman** [hewettp/GrampsCrossing#3]
I apologize if this bug is idiosyncratic to me, but when I run the program on Windows 10 from the command prompt (go to directory with program and .cv file, enter `py GrampsCrossing.py mygraph.cv` (running python 3)), I get the following error:
```
Exception raised in subprocess call
[Errno 32] Broken pipe
Traceback (most recent call last):
  File "GrampsCrossing.py", line 98, in crossings
    result.stdin.write(''.join(df).encode())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GrampsCrossing.py", line 133, in <module>
    nr_cross_best = crossings(header + people + links + spouses + families)
  File "GrampsCrossing.py", line 103, in crossings
    print(''.join(list(result.stderr)))
TypeError: sequence item 0: expected str instance, bytes found
```
I apologize that I do not know much python, so I do not really understand the issue. I tried to diagnose it; didn't get very far. Let me know if I'm doing anything wrong; otherwise, fixing the bug would be appreciated. Thanks for reading.

**Comment by hewettp** [comment]
Hi
Thanks for your message.
Also, I do not know much python. A few years ago, I wrote this script to clean up some large relationship graphs that I was making with Gramps. My work is done using Linux, so I never tested the script on Windows. 
Some other people have helpfully added improvements to the python 2 version of the script. A version by Ron Johnson is available from the page linked below. It is for python 2 but I understand that it works on Windows, so may be of help for you.
[https://www.gramps-project.org/bugs/view.php?id=6184](https://www.gramps-project.org/bugs/view.php?id=6184)

Sorry I can't be more help, but I don't run Gramps or python on Windows.

Regards

Peter

**Comment by kagghu** [comment]
In my family tree there are people with special characters in their names like ő or ű.
The script crashed when loading the file with 
`UnicodeDecodeError: 'charmap' codec can't decode byte`
Changing line 47 to
   ` with open(sys.argv[1],  mode="r", encoding="utf-8") as f:`
fixed it for me.

**Comment by hgohel** [comment]
Ran into the same issue as @SLetterman and found the cause for it. On Windows `dot` is installed in the Gramps directory which isn't in the system path. The command line is formed without a full path to `dot` in [L88](https://github.com/hewettp/GrampsCrossing/blob/c16edece14c6c309e1b084f0bc381c98d88d848d/GrampsCrossing.py#L88) and [L94](https://github.com/hewettp/GrampsCrossing/blob/c16edece14c6c309e1b084f0bc381c98d88d848d/GrampsCrossing.py#L94), so the subprocess call fails and the exception is thrown. On Linux the script may work because dot is installed as a package and is found in the path.

Ideal resolution would be to detect the Gramps install directory and prepend the path to dot when forming the command, or at least detect whether dot is available and print a message otherwise. Short of that there are two quick alternatives:
1. Modify both those lines and add the full path to your Gramps install directory. Example with Gramps 5.1.4 installed in the standard location on Windows:
Line 88: `cmd = '"C:\\Program Files\\GrampsAIO64-5.1.4\\dot.exe" -v -Tpdf > gcf1.pdf'`
Modify line 94 similarly.
2. Modify the Windows PATH variable to include the Gramps install directory so that the script will find dot. If you do this, consider writing a wrapper script so that the PATH is changed only when you're running this script.

**Comment by hewettp** [comment]
Hello hgohel
Thank you for your message.
Unfortunately, I don't have access to test this on a Windows system. Can you advise the python command that will return the Gramps install directory in Windows ? The example you provide will work for Gramps version 5.1.4, but not for any other versions. 
Alternatively, what python command can be used to temporarily change the PATH?

Thank you

**Comment by hewettp** [comment]
Hello @hgohel - thank you for your comments. The function to find the path for dot.exe on Windows has been expanded. Hopefully this is more robust and durable.

**Comment by hgohel** [comment]
@hewettp Script continues to work on my system :) It took a bit longer probably searching for dot because I have a ton of applications in installed on my system, but again, the point is that it works. Thanks again.
